// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/app-config": {
            "get": {
                "description": "Returns the current app configuration including version info and feature flags",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "app-config"
                ],
                "summary": "Get application configuration",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/entity.AppConfig"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "entity.AppConfig": {
            "type": "object",
            "properties": {
                "api_base_url": {
                    "type": "string"
                },
                "current_app_version": {
                    "type": "string"
                },
                "features": {
                    "$ref": "#/definitions/entity.Features"
                },
                "latest_app_version": {
                    "type": "string"
                },
                "minimum_required_version": {
                    "type": "string"
                }
            }
        },
        "entity.Features": {
            "type": "object",
            "properties": {
                "ai_chat": {
                    "type": "boolean"
                },
                "biometric_login": {
                    "type": "boolean"
                },
                "dark_mode": {
                    "type": "boolean"
                },
                "push_notifications": {
                    "type": "boolean"
                }
            }
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "",
	BasePath:         "/api/v1",
	Schemes:          []string{"https", "http"},
	Title:            "Aria BE API",
	Description:      "Aria Backend API",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
